services:
  - type: web
    name: academy-platform
    runtime: python
    repo: https://github.com/fatimahmed095a-gif/academy-platform
    branch: main
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
