services:
  - type: web
    name: academy-platform
    runtime: python
    repo: https://github.com/fatimahmed095a-gif/academy-platform
    branch: main
    buildCommand: pip install flask flask-cors
    startCommand: python app.py
